config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'
  resources :gardens do
    resources :bookings, only: [:new, :create, :show, :destroy] 
    resources :reviews, only: [:create, :new]
end
  # list of bookings belonging to the user
  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :garden
    belongs_to :user
    has_many :reviews

    validates :date, presence: true, uniqueness: true
end

app/models/garden.rb
class Garden < ApplicationRecord
    has_many_attached :photos
    has_many :bookings, dependent: :destroy
    has_many :reviews, dependent: :destroy
    belongs_to :user
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?
    validates :name, :description, :price, :capacity, :city, :zipcode, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :description, presence: :true
  belongs_to :gardens
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :gardens
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def index
        @bookings = Booking.all
    end
    
    def new
        @garden = Garden.find(params[:garden_id])
        @booking = Booking.new
        @user = @garden.user
    end
    
    def create
      @garden = Garden.find(params[:garden_id])
      @booking = Booking.new(booking_params)
      if @booking.save
        redirect_to garden_booking_path(@garden, @booking), notice: 'Your garden was booked succesfully'
      else
        render :new
      end
    end
    
    def show
    end

    def edit
    end

    def update
    end

    def destroy 
      @booking.destroy

      redirect_to garden_bookings_path
    end

    private

    def booking_params
      params.require(:booking).permit(:date).merge(user: current_user, garden: @garden, status: 'Booked')
    end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = " \
        gardens.city @@ :query \
        OR gardens.zipcode @@ :query \
        OR gardens.name @@ :query \
        OR gardens.description @@ :query \
      "
      @gardens = Garden.where(sql_query, query: "%#{params[:query]}%")
    else
      @gardens = Garden.all
    end

    @markers = @gardens.map do |garden| 
      {
        lat: garden.latitude,
        lng: garden.longitude,
        infowindow: render_to_string(partial: "info_window", locals: { garden: garden })
      }
    end
  end

  def show
    @booking = Booking.new
    @user = @garden.user
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)
    if @garden.save
      redirect_to garden_path(@garden), notice: 'Garden was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @garden.update(garden_params)

    # no need for app/views/restaurants/update.html.erb
    redirect_to garden_path(@garden)
  end

  def destroy
    @garden.destroy

    redirect_to gardens_path(@garden)
  end

  private

  def garden_params

   params.require(:garden).permit(:name, :description, :address, :city, :zipcode, :price, :capacity, photos: []).merge(user: current_user)

  end

  def set_garden
    @garden = Garden.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.find(params[:id])
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @review = Review.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to  garden_path(@garden)
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for [ @garden, @booking ] do |f| %>
  <%= f.input :date, as: :date, html5: true %>
  <%= f.submit "Book this garden", class: "btn btn-primary" %>
<% end %>

app/views/bookings/show.html.erb
<div class="map"></div>

<div class="container-i">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1>Your garden was booked successfully!</h1>
        <p class="flat-show-address"></p>
      </div>
      <div class="flat-show-card">
        <h3>You've received a confirmation by email</h3>
        <p></p>
      </div>
    </div>

      <div class="garden-show-card">
        <div class="flex-align">
          <div class="flex">
            <div class="footer-links">
              <a href="#"><i class="fab fa-github"></i></a>
              <a href="#"><i class="fab fa-instagram"></i></a>
              <a href="#"><i class="fab fa-facebook"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-linkedin"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gardens/_form.html.erb
<div class="gardens-form">
  <%= simple_form_for(garden) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :zipcode %>
    <%= f.input :capacity %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/gardens/_info_window.html.erb
<h2><%= garden.name %></h2>
<p><%= garden.address %></p>

app/views/gardens/delete.html.erb
<h1>Index#delete</h1>
<p>Find me in app/views/index/delete.html.erb</p>

app/views/gardens/edit.html.erb
<div class="container-i">
    <%= render "form", garden: @garden %>

    <p><%= link_to "Cancel", garden_path(@garden) %></p>
    <p><%= link_to "Back to gardens", gardens_path %></p>
</div>

app/views/gardens/index.html.erb
<div class="container-i">
  <div class="list-title">
    <% if params[:query] %>
      <h1><strong>Gardens at <%= params[:query] %><strong></h1>
    <% else %>
      <h1>Our Gardens</h1>
    <% end %>
  </div>
  <div class="list-subtitle">
    <p><%= @gardens.count %> results in this list</p>
  </div>
  <div class="cards-i">
    <% @gardens.each do |garden| %>
      <div class="col-12">
        <div class="card-i">
          <div class="garden-card-image" style="background-image: url(https://source.unsplash.com/collection/560886)">
            <div class="card-infos">
              <div class="garden-card-title">
                <%= link_to garden.name, garden_path(garden) %>
              </div>
              <p><%= garden.address %>, <%= garden.zipcode %>, <%= garden.city %></p>
              <div class="flex-align">
                <div class="flex">
                  <i class="fas fa-user"><%= garden.capacity %></i>
                </div>
                <div class="flex ml-3">
                  <i class="fas fa-euro-sign"> <%= garden.price %></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="garden-btn">
      <%= link_to new_garden_path, class: "btn btn-success" do %>
        Create a new garden
      <% end %>
    <% end%>
  </div>
</div>
 

app/views/gardens/new.html.erb
<div class="container-i">
    <%= render "form", garden: @garden %>

    <p><%= link_to "Back to gardens", gardens_path %></p>
</div>

app/views/gardens/show.html.erb
<div class="container-i">
  <div class="garden-img m-1 p-3">
    <% @garden.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 400, width: 500, crop: :fill %>
    <% end %>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-9">
        <div class="card-ss m-1 p-3 bg-white">
            <p><%= @garden.address %>, <%= @garden.city %></p>
            <h1><%= @garden.name %></h1>
        </div>
        <div class="card-ss garden-show-card m-1 p-3 bg-white">
          <h3>A bit more about this garden...</h3>
          <p><%= @garden.description %></p>
        </div>
      </div>

      <div class="col-3">
        <div class="card-ss garden-show-card p-2 m-1 bg-white text-center">
          <h5>Book this garden</h5>
          <div class="book-btn">
            <%= simple_form_for [ @garden, @booking ] do |f| %>
              <%= f.input :date, as: :date, html5: true %>
              <%= f.submit "Book", class: "btn btn-success" %>
            <% end %>
          </div>
        </div>

        <div class="card-ss garden-show-card p-3 m-1 bg-white text-center">
          <h5>Details</h5>
            <div class="details-card">
              <p><i class="fas fa-user"></i><%= @garden.capacity %></p>
              <p><%= @garden.price %><i class="fas fa-euro-sign"></i></p>
            </div>
          <div class="flex">
            <% if @garden.user == current_user %>
              <%= link_to edit_garden_path(@garden), class: "btn btn-light" do %>
                Edit
              <% end %>
              <%= link_to "Delete", garden_path(@garden), class: "btn btn-light", method: :delete, data: { confirm: "Are you sure?" } %><% end %>
              <%= link_to gardens_path, class: "btn btn-light" do %>
                List
              <% end %>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="card-ss garden-show-card p-2 m-1 bg-white text-center">
              <h5>User area</h5>
                <div class="user-card">
                <% if @garden.user == current_user %>
                    <%= link_to edit_garden_path(@garden), class: "btn btn-light" do %>
                      Edit
                    <% end %>
                    <%= link_to "Delete", garden_path(@garden), class: "btn btn-light", method: :delete, data: { confirm: "Are you sure?" } %><% end %>
                    <%= link_to gardens_path, class: "btn btn-light" do %>
                      List
                  <% end %>
                </div>
          </div>
          <div class="card-ss garden-show-card p-2 m-1 bg-white text-center">
          <%= link_to new_garden_review_path(@garden), class: "btn btn-light" do %>
                Reviews
              <% end %>
              </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenRental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div id='<%=  "#{controller_name}-#{action_name}-background" %>' class="background">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title>GardenRental</title>

  <meta name="keywords" content="Garden, Brussels, rental">

  </head>
  <body>


  </body>
</html>

app/views/pages/home.html.erb
<div class="container-i">
  <div class="col-12">
    <div class="header">
      <h1>AirGardens</h1>
      <div class="content">
        <p>Whether you’re looking for a tree to relax below or an entire garden for the whole family, a warm welcome awaits</p>
      </div>
      <div class="search-form">
        <%= form_tag gardens_path, class: "form-inline my-2 my-lg-2 ", method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a garden"%>
          <%= submit_tag "Search", class: "btn btn-success my-2 my-sm-0" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container-i">
  <h2>Review me here</h2>

  <%= simple_form_for [ @garden, @review ] do |f| %>
    <%= f.input :description %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="info">
    <a href="#">How Gardens works</a>
    <a href="#">Support</a>
    <a href="#">Cancelations</a>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "garden.jpg", alt: "Garden" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="search-bar" id="navbarSearchContent">
    <div class="col-md-12">
    <% unless controller_name == 'pages' && action_name == 'home' %>
      <%= form_tag gardens_path, class: "form-inline my-2 my-lg-0", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a garden" %>
          <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
          <%= link_to "Our gardens", gardens_path, class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Gardens page", gardens_path, class: "dropdown-item" %>
            <%= link_to "Create new garden", new_garden_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>